const daysAgo = (days) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

export function createMockLeads() {
  return [
    {
      ID: "lead-john-smith",
      Name: "John Smith",
      Company: "TechNova Inc.",
      Email: "john@technova.com",
      Phone: "+1 234 567 8901",
      Value: 15000,
      Stage: "Proposal",
      LastContactedAt: daysAgo(6),
      CreatedAt: daysAgo(18),
      NotesTimeline: `[${daysAgo(6)}|Call]: Discussed pricing and decision timeline. Waiting for final approval from stakeholders. || [${daysAgo(9)}|Email]: Sent proposal deck with premium package options. || [${daysAgo(14)}|StageChange]: Moved to Proposal after discovery call.`,
    },
    {
      ID: "lead-sarah-cooper",
      Name: "Sarah Cooper",
      Company: "GreenTech Solutions",
      Email: "sarah@greentech.com",
      Phone: "+1 234 567 8902",
      Value: 25000,
      Stage: "Contacted",
      LastContactedAt: daysAgo(2),
      CreatedAt: daysAgo(10),
      NotesTimeline: `[${daysAgo(2)}|Email]: Replied with budget range and asked for implementation timeline. || [${daysAgo(5)}|Call]: Intro call went well. Strong founder fit.`,
    },
    {
      ID: "lead-mark-davis",
      Name: "Mark Davis",
      Company: "NextGen Corp.",
      Email: "mark@nextgen.example",
      Phone: "+1 234 567 8903",
      Value: 8500,
      Stage: "New",
      LastContactedAt: daysAgo(5),
      CreatedAt: daysAgo(5),
      NotesTimeline: `[${daysAgo(5)}|Note]: Added from referral. Needs first outreach.`,
    },
    {
      ID: "lead-olivia-chen",
      Name: "Olivia Chen",
      Company: "Northstar Labs",
      Email: "olivia@northstar.example",
      Phone: "+1 234 567 8904",
      Value: 42000,
      Stage: "Qualified",
      LastContactedAt: daysAgo(4),
      CreatedAt: daysAgo(21),
      NotesTimeline: `[${daysAgo(4)}|Meeting]: Confirmed use case and success criteria. || [${daysAgo(11)}|Call]: Deep discovery call with founder and ops lead.`,
    },
    {
      ID: "lead-nina-patel",
      Name: "Nina Patel",
      Company: "BrightPath Studio",
      Email: "nina@brightpath.example",
      Phone: "+1 234 567 8905",
      Value: 12000,
      Stage: "Won",
      LastContactedAt: daysAgo(1),
      CreatedAt: daysAgo(30),
      NotesTimeline: `[${daysAgo(1)}|StageChange]: Moved to Won. Invoice requested. || [${daysAgo(3)}|Email]: Accepted revised proposal.`,
    },
    {
      ID: "lead-ethan-wright",
      Name: "Ethan Wright",
      Company: "Harbor Analytics",
      Email: "ethan@harbor.example",
      Phone: "+1 234 567 8906",
      Value: 18000,
      Stage: "Lost",
      LastContactedAt: daysAgo(12),
      CreatedAt: daysAgo(34),
      NotesTimeline: `[${daysAgo(12)}|StageChange]: Moved to Lost. Timing is not right this quarter. || [${daysAgo(16)}|Call]: Procurement paused new tools.`,
    },
  ];
}
